version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks: 
    - mynetwork
    environment: 
    - MONGO_INITDB_ROOT_USERNAME=productListUser
    - MONGO_INITDB_ROOT_PASSWORD=productListPassword

  mongo_import:
    depends_on: 
    - mongodb
    build: ./database
    environment:
      - HOST=mongodb 
      - USERNAME=productListUser
      - PASSWORD=productListPassword
    networks: 
    - mynetwork

  api:
    build: ./api
    ports: 
      - 3000:3000
    networks: 
    - mynetwork
    environment: 
    - DB_URL=mongodb://productListUser:productListPassword@mongodb:27017/promotions?authSource=admin
    depends_on: 
      - mongo_import

  web:
    build: ./web
    ports: 
      - 8000:80
    networks: 
    - mynetwork
    depends_on: 
      - api

networks: 
    mynetwork: {}